config/routes.rb
Rails.application.routes.draw do
  get "contact_forms/new"
  get "contact_forms/create"
  get "pages/new"
  get "pages/create"
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "home#index"
  get "about", to: "pages#about", as: :about
  get "news", to: "pages#news", as: :news

  # Ресурс для контактної форми
  resources :contact_forms, only: [:new, :create]

  get "contacts", to: "contact_forms#new", as: :contacts
  post "contacts", to: "contact_forms#create"  # Додаємо маршрут для POST запиту

  # Ресурси для продуктів
  resources :products, only: [:index, :show, :new, :create] do

    resources :comments, only: [:create] do
      post 'reply', on: :member, to: 'comments#reply'
    end
  end

  # Ресурс для кошика
  # config/routes.rb
  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: :add
    delete 'remove/:id', to: 'carts#remove', as: :remove
    delete 'clear', to: 'carts#clear', as: :clear
    get 'checkout', to: 'carts#checkout', as: :checkout

    # Додайте маршрут для оновлення кількості товару
    patch 'update_quantity/:id', to: 'carts#update_quantity', as: :update_quantity

  end
  # Інші ресурси
  resources :orders, only: [:new, :create]
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :address, presence: true
  validates :delivery_method, presence: true
  validates :payment_method, presence: true

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @cart = current_user.cart
    @cart_items = @cart.cart_items
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @cart = current_user.cart
    @cart_items = @cart.cart_items


    if @cart_items.empty?
      flash.now[:alert] = "Ваш кошик порожній!"
      render :new and return
    end

    @order.total_price = @cart_items.sum { |item| item.quantity * item.product.price }
    # Створення order_items з cart_items
    @cart_items.each do |item|
      @order.order_items.build(product: item.product, quantity: item.quantity, price: item.product.price)
    end

    if @order.save
      puts "jffhvfjvfnjvn"
      # Очищення кошика після створення замовлення
      @cart.cart_items.destroy_all
      redirect_to root_path, notice: "Ваше замовлення успішно оформлено!"
    else
      puts "jffhvfjvfnjvn"
      flash.now[:alert] = "Не вдалося оформити замовлення. Перевірте введені дані."
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :email, :phone, :address, :delivery_method, :payment_method, :delivery_address, :total_price, :delivery_address, :comment)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<%# Виведення flash повідомлення %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<%= link_to 'Повернутися на головну', root_path, class: 'btn btn-primary' %>

app/views/orders/new.html.erb
<h1></h1>
<%= link_to "< Кошик", cart_path, class: "back-home-button" %>

  <h1>Оформлення замовлення</h1>

  <%= form_with model: @order, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "Ваше ім'я" %>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :email, "Ваш Email" %>
      <%= f.email_field :email, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :phone, "Телефон" %>
      <%= f.text_field :phone, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :address, "Адреса доставки" %>
      <%= f.text_field :address, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :delivery_method, "Спосіб доставки" %>
      <%= f.select :delivery_method, ["Нова пошта", "Укрпошта", "Кур'єр","Самовиніс"], {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :payment_method, "Спосіб оплати" %>
      <%= f.select :payment_method, ["Готівка", "Картка", "Накладний платіж"], {}, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :comment, "Коментар" %>
      <%= f.text_area :comment, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= f.submit "Підтвердити замовлення", class: "btn" %>
  </div>
  <% end %>