config/routes.rb
Rails.application.routes.draw do
  get "contact_forms/new"
  get "contact_forms/create"
  get "pages/new"
  get "pages/create"
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root "home#index"
  get "about", to: "pages#about", as: :about
  get "news", to: "pages#news", as: :news

  # Ресурс для контактної форми
  resources :contact_forms, only: [:new, :create]

  get "contacts", to: "contact_forms#new", as: :contacts
  post "contacts", to: "contact_forms#create"  # Додаємо маршрут для POST запиту

  # Ресурси для продуктів
  resources :products, only: [:index, :show, :new, :create] do

    resources :comments, only: [:create] do
      post 'reply', on: :member, to: 'comments#reply'
    end
  end

  # Ресурс для кошика
  # config/routes.rb
  resource :cart, only: [:show] do
    post 'add/:product_id', to: 'carts#add', as: :add
    delete 'remove/:id', to: 'carts#remove', as: :remove
    delete 'clear', to: 'carts#clear', as: :clear
    get 'checkout', to: 'carts#checkout', as: :checkout

    # Додайте маршрут для оновлення кількості товару
    patch 'update_quantity/:id', to: 'carts#update_quantity', as: :update_quantity

  end
  # Інші ресурси
  resources :orders, only: [:new, :create]
end

app/models/product.rb
class Product < ApplicationRecord
  # Асоціації
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :comments, dependent: :destroy

  # Завантаження зображень
  has_one_attached :image

  # Валідації
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :category, presence: true

  # Додаткові методи (за потреби)
  def in_stock?
    stock > 0
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create] # Лише авторизовані користувачі можуть створювати товари
  before_action :check_admin, only: [:new, :create] # Перевірка на адміністратора

  def index
    # Фільтрація за категорією
    if params[:category].present?
      @products = Product.where(category: params[:category])
    else
      @products = Product.all
    end

    # Пошук
    if params[:query].present?
      @products = @products.where("name LIKE ? OR category LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%")
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Товар успішно доданий!'
    else
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :category, :price, :description, :image)
  end

  def check_admin
    unless current_user&.role == 'admin'
      redirect_to root_path, alert: 'Тільки адміністратори можуть додавати товари.'
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<h1></h1>
<%= link_to "< На головну", root_path, class: "back-home-button" %>

<h1>Каталог товарів </h1> <% if user_signed_in? && current_user.admin? %>
  <%= link_to 'Додати товар', new_product_path, class: 'btn btn-primary' %>
<% else %>
  <p>Тільки адміністратор може додавати товар</p>
<% end %>


<div class="product-grid">
  <% @products.each do |product| %>
    <div class="product-item">
      <%#= image_tag product.image, alt: product.name, class: 'product-image' %>
      <% if product.image.attached? %>
        <%= image_tag product.image, alt: product.name, class: "product-image" %>
      <% else %>
        <p>No image</p>
      <% end %>
      <h3><%= product.name %></h3>

      <div class="product-bottom">
        <p class="product-price">Ціна: <%= product.price %> грн</p>
        <p><%= link_to 'Переглянути', product_path(product), class: 'product-link' %></p>
      </div>

    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1></h1>
<%= link_to "< На головну", root_path, class: "back-home-button" %>
<h1>Додати новий товар</h1>

<%= form_with model: @product, local: true do |form| %>
  <div class="form-container">
    <div class="form-group">
      <%= form.label :name, "Назва товару" %>
      <%= form.text_field :name, placeholder: "Введіть назву товару" %>
    </div>

    <div class="form-group">
      <%= form.label :description, "Опис товару" %>
      <%= form.text_area :description, placeholder: "Опис товару" %>
    </div>

    <div class="form-group">
      <%= form.label :price, "Ціна" %>
      <%= form.number_field :price, step: 0.01, placeholder: "Введіть ціну" %>
    </div>

    <div class="form-group">
      <%= form.label :category, "Категорія" %>
      <%= form.text_field :category, placeholder: "Введіть категорію" %>
    </div>

    <div class="form-group">
      <%= form.label :image, "Фото товару" %>
      <%= form.file_field :image %>
    </div>

    <div class="form-actions">
      <%= form.submit "Створити товар", class: "submit-btn" %>
    </div>
  </div>
<% end %>


app/views/products/show.html.erb
<h1></h1>
<%= link_to "< Каталог", products_path, class: "back-home-button" %>
<div class="product-page-container">
  <h1><%= @product.name %></h1>


  <div class="product-image-container">
    <%#= image_tag @product.image, alt: @product.name, class: "product-image" %>
    <% if @product.image.attached? %>
      <%= image_tag @product.image, alt: @product.name, class: "product-image" %>
    <% else %>
      <p>No image</p>
    <% end %>
  </div>

  <div class="product-info">
    <p class="product-description"><%= @product.description %></p>
    <p class="product-price">Ціна: <%= number_to_currency(@product.price, unit: "", delimiter: " ", format: "%n грн") %></p>


    <%= button_to 'Додати у кошик', add_cart_path(product_id: @product.id), method: :post, class: "btn-primary" %>
  </div>
</div>

<div class="comments-section">
  <div class="comments-header">
    <h3>Кількість коментарів (<%= @product.comments.count %>)</h3>
    <div class="comments-toggle">
      <span>Коментарі "<%= @comments_enabled ? 'ON' : 'OFF' %>"</span>
      <input type="checkbox" <%= @comments_enabled ? 'checked' : '' %> />
    </div>
  </div>

  <div class="add-comment">
    <h3>Додати коментар</h3>
    <%= render 'comments/form' %>
  </div>

  <div class="comments-list">
    <% @product.comments.where(parent_id: nil).each do |comment| %>
      <div class="comment-item">
        <div class="comment-author">
          <div class="author-info">
            <span class="author-name"><%= comment.user.present? ? comment.user.name : 'Анонім' %></span>
            <span class="comment-date"><%= time_ago_in_words(comment.created_at) %> ago</span>
          </div>
        </div>
        <div class="comment-content">
          <p><%= comment.content %></p>
          <div class="comment-actions">
            <a href="#">Оновити</a>
            <a href="#">Відповісти</a>
            <a href="#">Перекласти</a>
          </div>
        </div>
        <!-- Відображення відповідей -->
        <div class="replies">
          <% comment.replies.each do |reply| %>
            <div class="reply-item">
              <div class="reply-author">
                <div class="author-info">
                  <span class="author-name"><%= reply.user.present? ? reply.user.name : 'Анонім' %></span>
                  <span class="comment-date"><%= time_ago_in_words(reply.created_at) %> ago</span>
                </div>
              </div>
              <div class="reply-content">
                <p><%= reply.content %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>